### ISSUE TITLE
opening TAP device failed

### ISSUE THREAD

**Issue by jazzdd86** [mjuenema/docker-alpine-peervpn#3]
I configured the image with cap_add: ALL, --privileged and net=host. But it still doesn't start correctly, and exits with:

```
opening sockets...
   IPv4/UDP: ok.
opening TAP device...
   failed.
error: The TAP device could not be opened! This might be caused by:
- a missing TAP device driver,
- a blocked TAP device (try a different name),
- insufficient privileges (try running as the root/administrator user).
```

**Comment by mjuenema** [comment]
Thanks for reporting the problem.

What happens if you run the example in the README (just replace the 10.0.2.15 with the IP address of the docker0 interface - I should probably clarify this in the README)?
Then log into either of the two containers and try to ping the other one, e.g. `ping 172.16.1.2`. 

I wonder whether the problem you are experiencing is specific to my Docker image or a general Docker problem. What version of Docker are you running and what's your OS? For reference I run Docker 1.12.3 on Fedora Linux. I haven't tested the image with any other versions of Docker so I'd be curious to know if this may cause problems.

Regards

Markus

**Comment by jazzdd86** [comment]
Hi, nope was also a host issue. I don't know why but my Linux was running on an old kernel but did not have /lib/modules for that kernel - and therefore no TUN module. An update and reboot of the server did the trick.

**Comment by mjuenema** [comment]
Great, I am glad that you found the cause of the problem. And thanks for your interest in docker-alpine-peervpn. It is always nice to see when others show interest in one's projects on Github :-)

**Comment by mjuenema** [comment]
I now encounter the issue when I try to change from running the container `--privileged` to setting specific capabilities, i.e. ` --cap-add ...`. I am re-opening the issue because you might be interested in the eventual solution. See the [Travis-CI job](https://travis-ci.org/mjuenema/docker-alpine-peervpn/jobs/237391792) for details.

**Comment by mjuenema** [comment]
The solution is to create the `/dev/net/tun` device from inside the running container (`docker-entrypoint.sh`) and not in the Dockerfile.

Tested on [Travis-CI](https://travis-ci.org/mjuenema/docker-alpine-peervpn/builds/237399992).

**Comment by jazzdd86** [comment]
Thanks for working on this, I changed my docker compose file to use the specific capability. Great image btw.
